from .position      import Position
from .degree        import Degree
from .department    import Department
from .time_dim      import TimeDim
from .teacher       import Teacher
from .subject       import Subject
from .group         import Group
from .teaching_load import TeachingLoad
from .publication   import Publication
from .patent        import Patent
from .achievement   import Achievement
from .project       import Project
from .kpi_score     import KPIScore
from .kpi_detail    import KPIDetail
from .user          import User
